# -*- coding: utf-8 -*-
"""caliberation on infosys closing price data.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1klea0SsaiBDeP4F48ydHvAdS1My5T6yk
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

# 1. Load Data (No header, single column)
# Updated to use your specific filename 'Infy.txt'
data = pd.read_csv('Infy.txt', header=None, names=['Price'])
prices = data['Price'].values
N = len(prices) - 1

# 2. Calculate Log-returns
log_returns = np.log(prices[1:] / prices[:-1])

# 3. Parameter Estimation
# delta_t is the time step; for daily data, 1/252 is standard
delta_t = 1/252
mu_hat = (1 / delta_t) * np.mean(log_returns)
sigma_hat = np.sqrt((1 / ((N - 1) * delta_t)) * np.sum((log_returns - np.mean(log_returns))**2))

print(f"Calibrated Drift (mu_hat): {mu_hat:.4f}")
print(f"Calibrated Volatility (sigma_hat): {sigma_hat:.4f}")

# 4. Simulate Paths
future_days = 60
num_paths = 3
S0 = prices[-1] # Starting point is the last price in Infy.txt

paths = np.zeros((future_days, num_paths))

for path in range(num_paths):
    current_s = S0
    for day in range(future_days):
        epsilon = np.random.normal(0, 1)
        # The discretization of the GBM SDE
        current_s = current_s * np.exp((mu_hat - 0.5 * sigma_hat**2) * delta_t +
                                       sigma_hat * np.sqrt(delta_t) * epsilon)
        paths[day, path] = current_s

# 5. Plotting
plt.figure(figsize=(10, 6))
plt.plot(paths)
plt.title("Infosys Price: 3 Simulated Sample Paths (Calibrated to Infy.txt)")
plt.xlabel("Days into the future")
plt.ylabel("Simulated Price")
plt.grid(True)
plt.show()

