# -*- coding: utf-8 -*-
"""deployment.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZZd07su2CHzNGtsPtnd-aVypKXGl5hPK
"""

# importing libraries

import yfinance as yf
import pandas as pd
import matplotlib.pyplot as plt

from hedger import EmpiricalHedger_1
from hedger import EmpiricalHedger_2

print("Downloading historical market data...")

# Download daily close prices from Jan 2024 to May 2026
spot_raw = yf.download("^NSEI", start="2024-01-01", end="2026-05-01")['Close']
futures_raw = yf.download("GC=F", start="2024-01-01", end="2026-05-01")['Close']

# Production safety check: Extract just the raw data column if yfinance returns a multi-index
if isinstance(spot_raw, pd.DataFrame):
    spot_raw = spot_raw.iloc[:, 0]
if isinstance(futures_raw, pd.DataFrame):
    futures_raw = futures_raw.iloc[:, 0]

print("\n" + "="*40)
print(f"Raw Spot Data Points downloaded:    {len(spot_raw)}")
print(f"Raw Futures Data Points downloaded: {len(futures_raw)}")
print("="*40)

"""From the above cell result we can clearly see that the number of data points under spot price is different from future price hence while predicting such mis alignment we had included the prepare data function inside our engine for acurracy of results"""

# Instantiate your custom quantitative engine
engine_1 = EmpiricalHedger_1(
    spot_series=spot_raw,
    futures_series=futures_raw,
    asset_name="Nifty50_vs_Gold"
)

# Instantiate your custom quantitative engine
engine_2 = EmpiricalHedger_2(
    spot_series=spot_raw,
    futures_series=futures_raw,
    asset_name="Nifty50_vs_Gold"
)

"""now under each spot and and future series they have same no. of data points

For EmpiricalHedger_1 the calculations ->
"""

# A. Calculate and display the Global Static OLS baseline
static_h_star = engine_1.calculate_static_hedge_ratio()

# B. Run the 60-day moving loop to capture dynamic parameter shifts
rolling_metrics_df = engine_1.calculate_rolling_hedge_ratio(window=60)

"""for EmpiricalHedger_1"""

# Execute the risk compression metrics suite
performance_results = engine_1.evaluate_performance()

"""for EmpiricalHedger_2"""

# A. Calculate and display the Global Static OLS baseline
static_h_star = engine_2.calculate_static_hedge_ratio()

# B. Run the 60-day moving loop to capture dynamic parameter shifts
rolling_metrics_df = engine_2.calculate_rolling_hedge_ratio(window=60)

# Execute the risk compression metrics suite for engine_2, including dynamic rolling
performance_results_engine_2 = engine_2.evaluate_performance(rolling_df=rolling_metrics_df)