# -*- coding: utf-8 -*-
"""Hedger_updated.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1f-1YN6IXcvLWttm32b811l5QzKwnqFHP
"""

!pip install pykalman

import numpy as np
import pandas as pd
from pykalman import KalmanFilter

class EmpiricalHedger_Kalman:
    def __init__(self, spot_prices, futures_prices):
        # 1. Data Preparation
        self.data = pd.DataFrame({'S': spot_prices, 'F': futures_prices}).dropna()
        self.data['Delta_S'] = np.log(self.data['S'] / self.data['S'].shift(1))
        self.data['Delta_F'] = np.log(self.data['F'] / self.data['F'].shift(1))
        self.data.dropna(inplace=True)

    def estimate_hedge(self, Q=1e-5, R=1e-3):
        # 2. Kalman Estimation Logic
        # obs_y: (n_samples, 1)
        # obs_mat: (n_samples, 1, 1) to handle time-varying coefficients
        obs_y = self.data['Delta_S'].to_numpy().reshape(-1, 1)
        obs_mat = self.data['Delta_F'].to_numpy().reshape(-1, 1, 1)

        kf = KalmanFilter(
            transition_matrices=[1],
            observation_matrices=obs_mat,
            initial_state_mean=0,
            initial_state_covariance=1,
            transition_covariance=Q,
            observation_covariance=R
        )

        state_means, _ = kf.filter(obs_y)
        self.data['Hedge_Ratio'] = state_means.flatten()
        return self.data['Hedge_Ratio']

    def evaluate_performance(self):
        # 3. Integrated Evaluation Logic
        # Calculate hedged returns
        self.data['Hedged_Returns'] = self.data['Delta_S'] - (self.data['Hedge_Ratio'] * self.data['Delta_F'])

        # Metrics Calculation
        var_unhedged = self.data['Delta_S'].var()
        var_hedged = self.data['Hedged_Returns'].var()

        # Return dictionary with matching keys for your print statements
        return {
            "variance_reduction": 1.0 - (var_hedged / var_unhedged),
            "volatility_reduction": 1.0 - (np.sqrt(var_hedged) / np.sqrt(var_unhedged)),
            "var_95": np.percentile(self.data['Hedged_Returns'], 5)
        }

import yfinance as yf

# 1. Define tickers
nifty_ticker = '^NSEI'
gold_ticker = 'GC=F'

# 2. Download historical data
data = yf.download([nifty_ticker, gold_ticker], start="2023-01-01", end="2026-07-08")['Close']

# 3. Extract the Series
spot_prices = data[nifty_ticker]
futures_prices = data[gold_ticker]

# 4. Initialize your Engine
engine = EmpiricalHedger_Kalman(spot_prices, futures_prices)

# Run the class definition cell first!

# Then, re-run this instantiation:
engine = EmpiricalHedger_Kalman(spot_prices, futures_prices)

# Now run the estimation and evaluation
engine.estimate_hedge(Q=1e-5, R=1e-3)
results = engine.evaluate_performance()

# --- Step 1: Import ---
# (Using the code block above to define spot_prices and futures_prices)

# --- Step 2: Estimate ---
# We use Q=1e-5 (low process noise) to allow the hedge ratio
# to adapt only when there is a real, structural shift in the data.
engine.estimate_hedge(Q=1e-5, R=1e-3)

# --- Step 3: Evaluate ---
results = engine.evaluate_performance()

print("--- Evaluation Results ---")
print(f"Variance Reduction: {results['variance_reduction']:.2%}")
print(f"Hedged Volatility: {results['volatility_reduction']:.2%}")
print(f"Worst Daily Loss (VaR 95%): {results['var_95']:.4f}")

# --- Step 4: Visualize for your Professor ---
import matplotlib.pyplot as plt
engine.data['Hedge_Ratio'].plot(figsize=(10, 5), title="Kalman-Optimized Dynamic Hedge Ratio")
plt.show()

