# -*- coding: utf-8 -*-
"""Hedger.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1q1hfvjgpMRG6vdkO8vZ-Rn6D8IR3xhuf
"""

# importing essential packages for engine

import pandas as pd
import numpy as np
import statsmodels.api as sm

"""# model without rolling hedge evaluation"""

# full integrated production code model -1

class EmpiricalHedger_1:
    """
    A production-grade Quantitative Engine to calculate, optimize,
    and backtest cross-hedging strategies using historical market data.
    """
    def __init__(self, spot_series: pd.Series, futures_series: pd.Series, asset_name: str = "Asset"):
        self.asset_name = asset_name
        self.data = None
        self.static_hedge_ratio = None
        self.hedge_effectiveness = None

        self._prepare_data(spot_series, futures_series)

    def _prepare_data(self, spot: pd.Series, futures: pd.Series):
        df = pd.DataFrame({'Spot': spot, 'Futures': futures}).dropna()
        # calculating the daily absolute difference
        df['Delta_S'] = df['Spot'].diff()
        df['Delta_F'] = df['Futures'].diff()

        # obtaining data with proper alignment
        self.data = df.dropna()
        print(f"[SUCCESS] Data Engine initialized for {self.asset_name}.")
        print(f"Perfect horizontally aligned data points: {len(self.data)} trading days.")

    def calculate_static_hedge_ratio(self) -> float:
        X = self.data['Delta_F'] # Independent variable
        Y = self.data['Delta_S'] # Dependent variable
        X_with_constant = sm.add_constant(X)
        model = sm.OLS(Y, X_with_constant).fit()

        self.static_hedge_ratio = model.params['Delta_F'] # slope of the OLS regression
        self.hedge_effectiveness = model.rsquared  # coefficient of determination of the OLS regression

        print("\n" + "="*50)
        print(f"--- STATIC HEDGE ANALYSIS FOR {self.asset_name.upper()} ---")
        print(f"Optimal Static Hedge Ratio (h*): {self.static_hedge_ratio:.4f}")
        print(f"Hedge Effectiveness (R-squared): {self.hedge_effectiveness * 100:.2f}%")
        print("="*50)
        return self.static_hedge_ratio

    def calculate_rolling_hedge_ratio(self, window: int = 60) -> pd.DataFrame:
        if len(self.data) < window:
            raise ValueError(f"Window size of {window} exceeds available data length of {len(self.data)}.")
        rolling_results = []
        timestamps = []
        for i in range(window, len(self.data)):
            window_data = self.data.iloc[i-window:i]
            X = window_data['Delta_F']
            Y = window_data['Delta_S']
            X_with_constant = sm.add_constant(X)
            model = sm.OLS(Y, X_with_constant, missing='drop').fit()

            timestamps.append(self.data.index[i])
            rolling_results.append({
                'Rolling_Hedge_Ratio': model.params['Delta_F'],
                'Rolling_Hedge_Effectiveness': model.rsquared
            })
        rolling_df = pd.DataFrame(rolling_results, index=timestamps)
        print("\n" + "="*50)
        print(f"--- DYNAMIC ROLLING HEDGE ANALYSIS COMPLETED ---")
        print(f"Total calculated rolling windows: {len(rolling_df)}")
        print(f"Average Rolling Hedge Ratio: {rolling_df['Rolling_Hedge_Ratio'].mean():.4f}")
        print(f"Average Rolling Effectiveness: {rolling_df['Rolling_Hedge_Effectiveness'].mean() * 100:.2f}%")
        print("="*50)
        return rolling_df

    def evaluate_performance(self) -> dict:
        if self.static_hedge_ratio is None:
            raise ValueError("Static hedge ratio must be calculated before evaluating performance.")
        unhedged_returns = self.data['Delta_S']
        hedged_returns = self.data['Delta_S'] - (self.static_hedge_ratio * self.data['Delta_F'])

        var_unhedged = unhedged_returns.var()
        var_hedged = hedged_returns.var()
        variance_reduction = 1.0 - (var_hedged / var_unhedged)

        var_95_unhedged = np.percentile(unhedged_returns, 5)
        var_95_hedged = np.percentile(hedged_returns, 5)
        basis_risk = (self.data['Spot'] - self.data['Futures']).std()

        metrics = {
            'unhedged_variance': var_unhedged,
            'hedged_variance': var_hedged,
            'variance_reduction': variance_reduction,
            'unhedged_95_var': var_95_unhedged,
            'hedged_95_var': var_95_hedged,
            'basis_risk': basis_risk
        }
        print("\n" + "="*50)
        print(f"--- RISK PERFORMANCE EVALUATION: {self.asset_name.upper()} ---")
        print(f"Variance Reduction achieved: {variance_reduction * 100:.2f}%")
        print(f"Basis Risk Volatility: {basis_risk:.4f}")
        print("-" * 50)
        print(f"95% 1-Day Downside VaR (Unhedged): {var_95_unhedged:.4f}")
        print(f"95% 1-Day Downside VaR (Hedged):   {var_95_hedged:.4f}")
        print(f"VaR Risk Compression: {abs(var_95_hedged - var_95_unhedged) / abs(var_95_unhedged) * 100:.2f}% improvement")
        print("="*50)
        return metrics

"""# model with rolling hedge evaluation

"""

import statsmodels.api as sm
import numpy as np
import pandas as pd

class EmpiricalHedger_2:
    """
    A production-grade Quantitative Engine to calculate, optimize,
    and backtest cross-hedging strategies using historical market data.
    """
    def __init__(self, spot_series: pd.Series, futures_series: pd.Series, asset_name: str = "Asset"):
        self.asset_name = asset_name
        self.data = None
        self.static_hedge_ratio = None
        self.hedge_effectiveness = None

        self._prepare_data(spot_series, futures_series)

    def _prepare_data(self, spot: pd.Series, futures: pd.Series):
        df = pd.DataFrame({'Spot': spot, 'Futures': futures}).dropna()
        # calculating the daily absolute difference
        df['Delta_S'] = df['Spot'].diff()
        df['Delta_F'] = df['Futures'].diff()

        # obtaining data with proper alignment
        self.data = df.dropna()
        print(f"[SUCCESS] Data Engine initialized for {self.asset_name}.")
        print(f"Perfect horizontally aligned data points: {len(self.data)} trading days.")

    def calculate_static_hedge_ratio(self) -> float:
        X = self.data['Delta_F'] # Independent variable
        Y = self.data['Delta_S'] # Dependent variable
        X_with_constant = sm.add_constant(X)
        model = sm.OLS(Y, X_with_constant).fit()

        self.static_hedge_ratio = model.params['Delta_F'] # slope of the OLS regression
        self.hedge_effectiveness = model.rsquared  # coefficient of determination of the OLS regression

        print("\n" + "="*50)
        print(f"--- STATIC HEDGE ANALYSIS FOR {self.asset_name.upper()} ---")
        print(f"Optimal Static Hedge Ratio (h*): {self.static_hedge_ratio:.4f}")
        print(f"Hedge Effectiveness (R-squared): {self.hedge_effectiveness * 100:.2f}%")
        print("="*50)
        return self.static_hedge_ratio

    def calculate_rolling_hedge_ratio(self, window: int = 60) -> pd.DataFrame:
        if len(self.data) < window:
            raise ValueError(f"Window size of {window} exceeds available data length of {len(self.data)}.")
        rolling_results = []
        timestamps = []
        for i in range(window, len(self.data)):
            window_data = self.data.iloc[i-window:i]
            X = window_data['Delta_F']
            Y = window_data['Delta_S']
            X_with_constant = sm.add_constant(X)
            model = sm.OLS(Y, X_with_constant, missing='drop').fit()

            timestamps.append(self.data.index[i])
            rolling_results.append({
                'Rolling_Hedge_Ratio': model.params['Delta_F'],
                'Rolling_Hedge_Effectiveness': model.rsquared
            })
        rolling_df = pd.DataFrame(rolling_results, index=timestamps)
        print("\n" + "="*50)
        print(f"--- DYNAMIC ROLLING HEDGE ANALYSIS COMPLETED ---")
        print(f"Total calculated rolling windows: {len(rolling_df)}")
        print(f"Average Rolling Hedge Ratio: {rolling_df['Rolling_Hedge_Ratio'].mean():.4f}")
        print(f"Average Rolling Effectiveness: {rolling_df['Rolling_Hedge_Effectiveness'].mean() * 100:.2f}%")
        print("="*50)
        return rolling_df

    def evaluate_performance(self, rolling_df: pd.DataFrame = None) -> dict:
        if self.static_hedge_ratio is None:
            raise ValueError("Static hedge ratio must be calculated before evaluating performance.")

        metrics = {}

        # --- Unhedged Performance ---
        unhedged_returns = self.data['Delta_S']
        var_unhedged = unhedged_returns.var()
        var_95_unhedged = np.percentile(unhedged_returns, 5)
        metrics['unhedged_variance'] = var_unhedged
        metrics['unhedged_95_var'] = var_95_unhedged

        print("\n" + "="*50)
        print(f"--- RISK PERFORMANCE EVALUATION: {self.asset_name.upper()} ---")

        # Added print statements for unhedged performance
        print("\n--- Unhedged Performance ---")
        print(f"95% 1-Day Downside VaR (Unhedged):   {var_95_unhedged:.4f}")

        # --- Static Hedging Performance ---
        print("\n--- Static Hedging ---")
        hedged_returns_static = self.data['Delta_S'] - (self.static_hedge_ratio * self.data['Delta_F'])

        var_hedged_static = hedged_returns_static.var()
        variance_reduction_static = 1.0 - (var_hedged_static / var_unhedged)
        var_95_hedged_static = np.percentile(hedged_returns_static, 5)

        metrics['static_hedged_variance'] = var_hedged_static
        metrics['static_variance_reduction'] = variance_reduction_static
        metrics['static_hedged_95_var'] = var_95_hedged_static

        print(f"Variance Reduction (Static Hedge): {variance_reduction_static * 100:.2f}%")
        print(f"95% 1-Day Downside VaR (Static Hedged):   {var_95_hedged_static:.4f}")
        print(f"VaR Risk Compression (Static Hedge): {abs(var_95_hedged_static - var_95_unhedged) / abs(var_95_unhedged) * 100:.2f}% improvement")

        # --- Dynamic Rolling Hedging Performance (if rolling_df is provided) ---
        if rolling_df is not None:
            print("\n--- Dynamic Rolling Hedging ---")
            # Align self.data with rolling_df's index
            # Use the rolling hedge ratio for each day's delta calculation
            aligned_data = self.data.loc[rolling_df.index]
            hedged_returns_dynamic = aligned_data['Delta_S'] - (rolling_df['Rolling_Hedge_Ratio'] * aligned_data['Delta_F'])

            # Calculate metrics for dynamic hedging
            var_hedged_dynamic = hedged_returns_dynamic.var()
            variance_reduction_dynamic = 1.0 - (var_hedged_dynamic / var_unhedged) # Compare to overall unhedged
            var_95_hedged_dynamic = np.percentile(hedged_returns_dynamic, 5)

            metrics['dynamic_hedged_variance'] = var_hedged_dynamic
            metrics['dynamic_variance_reduction'] = variance_reduction_dynamic
            metrics['dynamic_hedged_95_var'] = var_95_hedged_dynamic

            print(f"Variance Reduction (Dynamic Hedge): {variance_reduction_dynamic * 100:.2f}%")
            print(f"95% 1-Day Downside VaR (Dynamic Hedged):   {var_95_hedged_dynamic:.4f}")
            print(f"VaR Risk Compression (Dynamic Hedge): {abs(var_95_hedged_dynamic - var_95_unhedged) / abs(var_95_unhedged) * 100:.2f}% improvement")

        # --- Basis Risk (Calculated once for the entire period) ---
        basis_risk = (self.data['Spot'] - self.data['Futures']).std()
        metrics['basis_risk'] = basis_risk

        print("\n" + "-" * 50)
        print(f"Basis Risk Volatility: {basis_risk:.4f}")
        print("="*50)
        return metrics

















