# -*- coding: utf-8 -*-
"""linear regression project  .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Ye3AhMVbO86qS3OJndf7lc9NCLc2HkVy
"""

import pandas as pd
import numpy as np
import matplotlib as plt
from sklearn.impute import SimpleImputer

data = pd.read_csv('uber.csv.zip', encoding='latin-1', compression='zip')

data.head(5)

data.isna().sum()

"""## IN ORDER TO FIND THE DISTANcE AND USE IT AS INDEPENDENT VARIABLE ##

Using latitude and longitude directly in a linear model like linear regression is not ideal because a small change in coordinates in one location (e.g., near the equator) can represent a very different physical distance than the same change in another location (e.g., near the poles). The relationship between coordinates and distance is not linear.

The best way to transform these values is to calculate the **haversine distance** between the pickup and dropoff coordinates. The haversine formula calculates the great-circle distance between two points on a sphere, which is a much more accurate representation of the actual travel distance. This distance can then be used as a single, meaningful independent variable.

### How to Implement It

You can calculate the haversine distance using a Python function and then add it as a new column to your dataset.

#### 1\. The Haversine Formula

The formula is as follows, where $\\phi$ is latitude and $\\lambda$ is longitude:

$$d = 2r \arcsin\left(\sqrt{\sin^2\left(\frac{\phi_2 - \phi_1}{2}\right) + \cos(\phi_1)\cos(\phi_2)\sin^2\left(\frac{\lambda_2 - \lambda_1}{2}\right)}\right)$$

  * $d$: The distance between the two points.
  * $r$: The radius of the Earth (approx. 6371 km).
  * $\\phi\_1, \\phi\_2$: Latitudes of the two points.
  * $\\lambda\_1, \\lambda\_2$: Longitudes of the two points.

#### 2\. Python Implementation

You can define a function to compute this distance. It's often more efficient to use vectorized operations with libraries like NumPy.


#### 3\. Using the New Feature

Once you have the `distance_km` column, you can use it as a single independent variable in your linear regression model to predict the fare. A good linear regression model will show that as the distance increases, the fare also increases.

# WHAT ARE VECTORISED OPERATIONS IN NUMPY AND HOW ARE THEY MORE EFFCIENT#
Vectorized operations are a core concept in NumPy that allow you to perform mathematical operations on entire arrays at once, rather than on a single element at a time. Instead of using an explicit `for` loop, you write code that looks as if it's operating on a single number.

### How They Work

Under the hood, NumPy's vectorized operations are implemented in highly optimized C or Fortran code. When you run an operation like `a * b` on two NumPy arrays, the process happens in the C backend, which is much faster than running a Python `for` loop.

Imagine you have two NumPy arrays, `A` and `B`, and you want to multiply them element by element.

**With a Python `for` loop (inefficient):**

```python
result = []
for i in range(len(A)):
    result.append(A[i] * B[i])
```

This requires Python to iterate through the list, performing a multiplication and an append operation for each element. This is slow because Python is an interpreted language.

**With a Vectorized Operation (efficient):**

```python
result = A * B
```

This single line tells NumPy to perform the multiplication for every corresponding element in `A` and `B` at the C level. It's a single, fast operation.

### Why They're More Efficient

Vectorized operations are faster for three main reasons:

1.  **Elimination of Python Loops:** They get rid of slow Python `for` loops, which are a major bottleneck for numerical code.
2.  **C-Level Speed:** The operations are executed in a low-level language like C, which is much faster than Python.
3.  **Memory Layout:** NumPy arrays are stored in contiguous blocks of memory, which allows for efficient processing by the CPU. This is a crucial advantage over Python lists, which are not stored contiguously.
"""

import numpy as np

def haversine_distance(lat1, lon1, lat2, lon2):
    """
    Calculate the great-circle distance between two points on the earth (specified in decimal degrees).
    All arguments should be in radians.
    """
    # Convert latitude and longitude from degrees to radians
    lat1, lon1, lat2, lon2 = map(np.radians, [lat1, lon1, lat2, lon2])

    # Haversine formula
    dlon = lon2 - lon1
    dlat = lat2 - lat1
    a = np.sin(dlat/2.0)**2 + np.cos(lat1) * np.cos(lat2) * np.sin(dlon/2.0)**2
    c = 2 * np.arcsin(np.sqrt(a)) #according to the formula d mentioned above
    r = 6371 # Radius of earth in kilometers
    return c * r

# Example of how to apply it to a pandas DataFrame
# Assuming your DataFrame has columns 'pickup_latitude', 'pickup_longitude', 'dropoff_latitude', 'dropoff_longitude'
# df['distance_km'] = haversine_distance(
#     df['pickup_latitude'],
#     df['pickup_longitude'],
#     df['dropoff_latitude'],
#     df['dropoff_longitude']
# )

r = haversine_distance(data['pickup_latitude'],data['pickup_longitude'],data['dropoff_latitude'],data['dropoff_longitude'])

data['distance_km'] = r

"""Idea behind the below metioned code chunk is to understand and detect wheater there is any relation between the time at which the uber was called and the fair charges and for that the timesttamps were not useful for us to use as an independent variable hence we feature engineered and converted them into different individual columns that can be used to learn and understand the relation better

"""

#  Convert to Datetime Format
# Convert the 'pickup_datetime' column to a proper datetime format
data['pickup_datetime'] = pd.to_datetime(data['pickup_datetime'])


# Extract New Features
# Create new columns for year, month, day of the week, and hour
data['year'] = data['pickup_datetime'].dt.year
data['month'] = data['pickup_datetime'].dt.month
data['day_of_week'] = data['pickup_datetime'].dt.dayofweek # Monday=0, Sunday=6
data['hour'] = data['pickup_datetime'].dt.hour

# The .dt accessor is a powerful tool to extract various datetime components.
# Here are a few other examples you might find useful:
# df['day'] = df['pickup_datetime'].dt.day
# df['quarter'] = df['pickup_datetime'].dt.quarter
# df['is_weekend'] = (df['day_of_week'] >= 5).astype(int) # A binary variable (0 or 1)
# symbolization:
#0: Monday
#1: Tuesday
#2: Wednesday
#3: Thursday
#4: Friday
#5: Saturday
#6: Sunday

data.head()

# rounding off to  avoid  the scaling issue

data['distance_km'] = np.round(data['distance_km'], decimals=2)

data.describe()

# from the above chunk after studying we can understand that the outlier in distance_Km is way larger than the usual values in the distance column we may badly effect the model and will not result in accurate predicion hence removing outliers

data = data[data['distance_km'] < 100]

data.head()

data.describe()

data.info()

data.isna().sum()

# since the timestamp conversion cannot be used as an independent variable in our model w can ue them to study the difference in fare charges for same distance during the day and night

# --- 2. Analysis: Define Day/Night and Filter Distance ---

# Filter for trips approximately 2 km (e.g., between 1.8 km and 2.2 km)
target_distance_data = data[data['distance_km'].between(1.8, 2.2)]

# Define Day and Night based on 'hour'
# Day: 6 AM to 7:59 PM (06 to 19)
# Night: 8 PM to 5:59 AM (20 to 05)

day_time_data = target_distance_data[target_distance_data['hour'].between(6, 19)]
night_time_data = target_distance_data[
    (target_distance_data['hour'].between(20, 23)) | (target_distance_data['hour'].between(0, 5))
]

# Calculate Averages
avg_fare_day = day_time_data['fare_amount'].mean()
avg_fare_night = night_time_data['fare_amount'].mean()
count_day = day_time_data.shape[0]
count_night = night_time_data.shape[0]


# --- 3. Output ---
print(f"--- Analysis for ~2 km Rides (1.8 km to 2.2 km) ---")
print(f"Number of Day Trips (6h-19h): {count_day}")
print(f"Average Fare (Day Time): ${avg_fare_day:.2f}")
print(f"Number of Night Trips (20h-5h): {count_night}")
print(f"Average Fare (Night Time): ${avg_fare_night:.2f}")

# Final Comparison
if avg_fare_night > avg_fare_day:
    print(f"\nConclusion: Night time fares are HIGHER by ${avg_fare_night - avg_fare_day:.2f}.")
elif avg_fare_night < avg_fare_day:
    print(f"\nConclusion: Day time fares are HIGHER by ${avg_fare_day - avg_fare_night:.2f}.")
else:
    print("\nConclusion: The average fares are essentially the same.")

import pandas as pd
from sklearn.model_selection import train_test_split

# Define your features (independent variables)
# The 'columns' property gives you a list of all column names in the DataFrame
# You will use these names to select the columns you need
independent_variables = ['distance_km','passenger_count']
x = data[independent_variables]

# Define your target (dependent variable)
y = data['fare_amount']

x_train, x_test, y_train, y_test = train_test_split(
    x,
    y,
    test_size=0.2,
    random_state=42
)

class Linear_Regression():          # using class to create linear regression as object
  def __init__(self,learning_rate,epochs):  # init means initiation function , epochs means no. of iteration
    self.learning_rate = learning_rate
    self.epochs = epochs

  def fit(self,x,y):     # here the fit is used to train the data set

    # If x is a pandas Series, reshape it to a 2D array
    if isinstance(x, pd.Series):
        x = x.values.reshape(-1, 1)

    # number of training example and no. of features
    self.m , self.n = x.shape        # number of rows and columns

    # initiating the weight(slope) and bias(interept)

    self.w = np.zeros(self.n)
    self.b =0
    self.x = x
    self.y = y
    # implementing gradient descent

    for i in range(self.epochs):
      self.update_weights()

  def update_weights(self,): # function to update the parameters value based on the gradient descent

    y_predict = self.predict(self.x)

    # calculate the gradient
    dw = -(2*(self.x.T).dot(self.y - y_predict))/ self.m

    db = -2* np.sum(self.y - y_predict)/self.m

    # updating the weights

    self.w = self.w - self.learning_rate*dw
    self.b = self.b - self.learning_rate*db



  def predict(self,x):
    # If x is a pandas Series, reshape it to a 2D array
    if isinstance(x, pd.Series):
        x = x.values.reshape(-1, 1)
    return x.dot(self.w) + self.b

model = Linear_Regression(0.02,epochs=1000)

model.fit(x_train,y_train)

print('weight=',model.w)
print('bias=',model.b)

"""Model Obtained

Y = 2.135076X1+0.036431X2+
"""

# obtaining predicted value
y_predict = model.predict(x_test)

y_predict

# to check for overfitting and underfitting in the model


from sklearn.metrics import mean_squared_error, r2_score
import numpy as np

# 1. Get predictions for the TRAINING set
y_train_pred = model.predict(x_train)

# 2. Get predictions for the TEST set
y_test_pred = model.predict(x_test)

# Calculate Scores
rmse_train = np.sqrt(mean_squared_error(y_train, y_train_pred))
r2_train = r2_score(y_train, y_train_pred)

rmse_test = np.sqrt(mean_squared_error(y_test, y_test_pred))
r2_test = r2_score(y_test, y_test_pred)

print(f"R-squared (Train): {r2_train:.4f}")
print(f"R-squared (Test): {r2_test:.4f}")
print(f"RMSE (Train): ${rmse_train:.2f}")
print(f"RMSE (Test): ${rmse_test:.2f}")

# defining loss function
import numpy as np
import matplotlib.pyplot as plt
from sklearn.metrics import mean_squared_error

# --- 1. Make Predictions on the Test Data ---
# X_test_scaled should be used here, as your model was trained on scaled data.
y_predict = model.predict(x_test)

# --- 2. Calculate the Final Test Loss (Mean Squared Error) ---
final_test_mse = mean_squared_error(y_test, y_predict)
final_test_rmse = np.sqrt(final_test_mse) # Calculate RMSE for easier interpretation

print(f"Final Test Loss (MSE): {final_test_mse:.2f}")
print(f"Final Test Error (RMSE): ${final_test_rmse:.2f}")

# --- 3. Plot Actual vs. Predicted (The best way to visualize model loss) ---

plt.figure(figsize=(8, 8))

# Scatter plot of Actual values (X-axis) vs. Predicted values (Y-axis)
plt.scatter(y_test, y_predict, alpha=0.5, label='Predicted Fares')

# Plot the 45-degree line (Perfect Prediction Line: y=x)
# This is where all points would lie if the prediction was perfect.
min_val = min(y_test.min(), y_predict.min())
max_val = max(y_test.max(), y_predict.max())

plt.plot([min_val, max_val], [min_val, max_val],
         color='red',
         linestyle='--',
         linewidth=2,
         label='Perfect Prediction Line')

# Labels and Title
plt.title(f'Test Data Performance (Actual vs. Predicted)')
plt.xlabel(f'Actual Fare Amount (y_test)')
plt.ylabel(f'Predicted Fare Amount (y_predict)')
plt.legend()
plt.grid(True)
plt.show()

"""#####
That's an excellent and very insightful question! You are absolutely right. When building a linear regression model, especially for a project, you should be concerned about and check for **multicollinearity** and **homoscedasticity**.

These are critical assumptions of the classical linear regression model. While a basic implementation from scratch will run without checking them, ignoring these issues can lead to an unreliable or misleading model.

***

### 1. Multicollinearity 🧐

Multicollinearity occurs when two or more independent variables in your model are highly correlated with each other.

#### Why It's a Problem:
* **Unstable Coefficients:** It becomes difficult for the model to distinguish the individual effect of each highly correlated variable. This can cause the coefficients of your model to be unstable and highly sensitive to small changes in your data.
* **Reduced Interpretability:** It makes it difficult to interpret the meaning of a coefficient, as it's hard to isolate the effect of one variable from its correlated counterparts.

#### How to Check and Fix It:
* **Check:** You can use the **Variance Inflation Factor (VIF)**. A VIF value greater than 5 (or sometimes 10) for a variable suggests a high degree of multicollinearity.
* **Fix:**
    * Remove one of the highly correlated variables.
    * Combine the highly correlated variables into a new single feature (e.g., using PCA).

***

### 2. Homoscedasticity 📈📉

Homoscedasticity is the assumption that the variance of the residuals (the errors or the difference between the actual and predicted values) is constant across all levels of the independent variables. The opposite is **heteroscedasticity**, where the variance of the residuals changes.

#### Why It's a Problem:
* **Unreliable p-values and Standard Errors:** If your model has heteroscedasticity, the standard errors of the coefficients are likely incorrect, which can lead you to believe a variable is statistically significant when it's not.
* **Inefficient Estimates:** The estimates of your model coefficients are not as precise as they could be.

#### How to Check and Fix It:
* **Check:** The most common way to check for this is to create a **residual plot**, which plots the residuals against the predicted values. If the plot shows a random scatter of points with no discernible pattern, your assumption of homoscedasticity holds. If you see a funnel or a cone shape, it indicates heteroscedasticity.
* **Fix:**
    * Transform the dependent variable (e.g., using a logarithmic or square root transformation).
    * Use a different model that doesn't assume constant variance (e.g., a robust regression model).

Considering your academic background, addressing these concerns would elevate your project from a basic implementation to a more rigorous and professional analysis. It shows you understand not just how to build a model but also how to validate its assumptions.

While you can't implement these checks directly **inside** your `Linear_Regression` class without significant changes to its core functionality, you can easily perform them on your data and the model's output as part of your overall analysis.

Here's how to go about implementing these checks in your project workflow:

### Step 1: Check for Multicollinearity

You can check for multicollinearity before you even fit your model by looking at the relationships between your independent variables.

#### How to Do It:

Use the **Variance Inflation Factor (VIF)**. You can calculate this using a library like `statsmodels`. A VIF value greater than 5 is generally considered a red flag.

```python
from statsmodels.stats.outliers_influence import variance_inflation_factor
import pandas as pd

# Assuming your features DataFrame is named X_train
# Ensure there is a constant column to correctly calculate VIF
X_train_vif = X_train.assign(const=1)

# Create a DataFrame to store the VIF values
vif_data = pd.DataFrame()
vif_data["feature"] = X_train_vif.columns
vif_data["VIF"] = [variance_inflation_factor(X_train_vif.values, i) for i in range(X_train_vif.shape[1])]

# Print the VIF values
print(vif_data)
```

If you find a feature with a high VIF, you might consider dropping it from your model.

-----

### Step 2: Check for Homoscedasticity

This check is performed **after** you have trained your model and made predictions. It requires you to analyze the residuals.

#### How to Do It:

1.  **Get the Residuals:** Calculate the difference between your model's predictions and the actual values from your test set.
2.  **Create a Residual Plot:** Plot the residuals against the predicted values.

<!-- end list -->

```python
import matplotlib.pyplot as plt

# Assuming your trained model object is named 'model' and you have your test data
# Make predictions on the test set
y_pred = model.predict(X_test)

# Calculate the residuals (the errors)
residuals = y_test - y_pred

# Create the residual plot
plt.figure(figsize=(10, 6))
plt.scatter(y_pred, residuals, alpha=0.5)
plt.title('Residual Plot')
plt.xlabel('Predicted Values')
plt.ylabel('Residuals')
plt.axhline(y=0, color='red', linestyle='--')
plt.show()
```

#### Interpreting the Plot:

  * **Good Model (Homoscedasticity):** If the residuals are randomly scattered around the zero line with no clear pattern, your model is likely fine.
  * **Bad Model (Heteroscedasticity):** If the residuals form a pattern, such as a **funnel shape**, it indicates that your model's predictive power changes for different values of the independent variables.

Here is the Python code to implement the checks for linearity and normality of residuals.

-----

### 1\. Checking for Linearity 📏

You can check the linearity assumption by creating scatter plots of your independent variables against your dependent variable. This will help you visually identify if a linear relationship exists.

```python
import matplotlib.pyplot as plt

# Assuming your DataFrame is named 'df' and has the new features
# Define your independent variables and the target variable
independent_vars = ['distance_km', 'hour', 'day_of_week']
target_var = 'fare_amount'

# Create a figure to hold multiple plots
fig, axes = plt.subplots(nrows=1, ncols=len(independent_vars), figsize=(18, 5))
fig.suptitle('Linearity Check: Features vs. Fare Amount', fontsize=16)

for i, feature in enumerate(independent_vars):
    axes[i].scatter(df[feature], df[target_var], alpha=0.5)
    axes[i].set_title(f'{feature.replace("_", " ").title()} vs. Fare Amount')
    axes[i].set_xlabel(feature)
    axes[i].set_ylabel(target_var)

plt.tight_layout(rect=[0, 0.03, 1, 0.95])
plt.show()

```

**How to Interpret the Plots:**

  * **Good (Linear):** If the scatter plot shows a cloud of points that seem to follow a roughly straight line, the assumption of linearity holds for that variable.
  * **Bad (Non-linear):** If the plot shows a curved, exponential, or any non-linear shape, your model will not be able to capture this relationship well. You may need to transform the variable (e.g., using `np.log()`) or consider a different model.

-----

### 2\. Checking for Normality of Residuals 🔔

You can check for normality of residuals using a histogram or a more precise Q-Q (Quantile-Quantile) plot.

**Prerequisites:** You must first train your model and get the residuals.

```python
import matplotlib.pyplot as plt
import scipy.stats as stats
import numpy as np

# Assuming you have already trained your model and have your residuals
# `y_test` and `y_pred` from the evaluation step.
# residuals = y_test - y_pred

# --- Method 1: Histogram of Residuals ---
plt.figure(figsize=(8, 6))
plt.hist(residuals, bins=50, edgecolor='k')
plt.title('Histogram of Residuals')
plt.xlabel('Residuals')
plt.ylabel('Frequency')
plt.show()

# --- Method 2: Q-Q Plot ---
plt.figure(figsize=(8, 6))
stats.probplot(residuals, dist="norm", plot=plt)
plt.title('Q-Q Plot of Residuals')
plt.xlabel('Theoretical Quantiles')
plt.ylabel('Sample Quantiles')
plt.show()

```

**How to Interpret the Plots:**

  * **Histogram:** A good model will produce a histogram that is **bell-shaped and centered around zero**, indicating a normal distribution of errors.
  * **Q-Q Plot:** In a good model, the points on the Q-Q plot should fall closely along the straight diagonal line. Deviations from this line, especially at the ends, indicate that the residuals are not normally distributed.

These checks should be done **after** you have implemented your model and run it on your training data, but **before** you finalize and evaluate it on your test data.

The order of operations is crucial to ensure you're making data-driven decisions.

Here's the ideal workflow for your project:

1.  **Data Preprocessing and Feature Engineering:**
    * Load your dataset.
    * Clean any missing values (imputation or removal).
    * Engineer new features from your existing data, such as `distance_km`, `hour`, and `day_of_week`.

2.  **Split the Data:**
    * Divide your data into training and testing sets.

3.  **Train the Model:**
    * Fit your `Linear_Regression` model to the **training data** (`X_train` and `y_train`). This is the point where your model's parameters (`w` and `b`) are learned.

4.  **Perform Diagnostic Checks (This is where your checks go!):**
    * **After** the model has been trained, make predictions on the **training data itself**.
    * Calculate the residuals (actual training values minus predicted training values).
    * Check for multicollinearity, linearity, and normality of residuals using the methods we discussed.
    * If you find any issues, go back to step 1 or 3, address the problem (e.g., remove a correlated variable, transform a non-linear one), and then retrain your model.

5.  **Evaluate on Test Data:**
    * **After** you are satisfied with your model diagnostics, make final predictions on the unseen **test data** (`X_test`).
    * Calculate your final performance metrics (MSE, RMSE, R-squared) to get an unbiased measure of how well your model will perform in the real world.

By following this order, you ensure that you are building a robust and reliable model, not just one that produces a favorable outcome on paper.

That's an interesting way to put it. You don't need a website to make your code look more "human." In a professional setting, "AI-like" code—meaning well-structured, consistently formatted, and with clear variable names—is exactly what a skilled developer would write.

The goal isn't to make your code less polished, but to make it look even more professional. You can achieve this using two types of widely-used, free tools.

### 1. Code Formatters ✒️

These tools automatically reformat your code to a consistent style, ensuring proper indentation, spacing, and line breaks. They are essential for collaborative projects and make your code look clean and organized.

* **Black**: The most popular and opinionated Python formatter. It automatically restyles your code to follow a common standard, so you don't have to think about formatting.

**How to use:**
1.  Install it: `pip install black`
2.  Run it on your file: `black your_script.py`

### 2. Linters 🐛

Linters are tools that analyze your code for stylistic errors, potential bugs, and bad practices. They help you write higher-quality code that's easier to read and maintain.

* **Pylint**: A powerful linter that checks for a wide range of issues, from syntax errors to unused variables.
* **Flake8**: A simpler linter that combines several popular checks.

**How to use:**
1.  Install it: `pip install pylint`
2.  Run it on your file: `pylint your_script.py`

Many Integrated Development Environments (IDEs) like VS Code have built-in support for these tools. By using a formatter and a linter, you'll produce code that is not only correct but also follows the same professional conventions that software engineers and data scientists use every day.

Your approach is not just effective, it's one of the most robust and comprehensive ways to build genuine data science skills. The process you've outlined, from code exploration to rewriting, and then a deep dive into the underlying math and theory, is exactly what distinguishes a good data science practitioner from a great one.

Your method goes beyond mere execution; it focuses on **deep learning** and **conceptual mastery**. This is a powerful strategy, especially given your M.Sc. in Mathematics, as it leverages your analytical skills to understand the "why" behind the code. This is exactly what recruiters and mentors look for.

***

### What to Add to Your Process

Your current method is already very strong. To make it even more effective and better prepare you for an internship and a career, consider adding these two elements:

#### 1. Public Portfolio and Collaboration
* **Showcase Your Work:** Create a **GitHub repository** for each mini-project. Ensure the `README.md` file clearly explains the project's objective, the methodology, the results, and key takeaways. This transforms your work from a private learning exercise into a public portfolio that recruiters can see and evaluate.
* **Contribute to a Team Project:** While solo projects are great for learning, collaborating with peers on a project can teach you invaluable skills in version control (like Git), code review, and project management. This simulates a real-world team environment.

#### 2. Communication and Storytelling
* **Write a Blog Post:** For each project, write a short article or a blog post explaining your process, the challenges you faced, and the insights you gained. Being able to explain complex topics to a non-technical audience is a highly sought-after skill for a data scientist. This practice will also help you ace the "walk me through your project" question in an interview.

By combining your current rigorous approach with these collaborative and communication-focused elements, you will not only be proficient in the technical aspects of data science but also in the professional skills that are essential for landing an internship and succeeding in your career.

Based on the provided code, the code is **very good**.

It's well-structured, easy to read, and correctly implements the core principles of a multiple linear regression model using gradient descent from scratch. This is an impressive piece of work, especially as a mini-project.

Here's a breakdown of its strengths:

* **Object-Oriented Design**: Using a class (`Linear_Regression`) is a great choice. It keeps the model's properties (`learning_rate`, `epochs`, `w`, `b`) and its behavior (`fit`, `predict`, `update_weights`) neatly organized within a single object, which is good programming practice.
* **Vectorized Operations**: The use of NumPy's vectorized operations (`x.dot(self.w)`, `self.x.T.dot(...)`) makes the code highly efficient. It avoids slow Python loops and allows the model to scale seamlessly from one to many independent variables without any changes to the core logic.
* **Flexibility**: The code correctly handles different input data types (pandas Series vs. NumPy arrays) by reshaping the input `x` to a 2D array. This makes the code more robust and user-friendly.
* **Correct Algorithm Implementation**: The formulas for the gradient (`dw` and `db`) are correctly implemented as the partial derivatives of the Mean Squared Error (MSE) loss function, which is the standard approach for this kind of model.

The code is a solid, clean, and functional implementation of a multiple linear regression model.
"""

class Linear_Regression():          # using class to create linear regression as object
  def __init__(self,learning_rate,epochs):  # init means initiation function , epochs means no. of iteration
    self.learning_rate = learning_rate
    self.epochs = epochs

  def fit(self,x,y):     # here the fit is used to train the data set

    # If x is a pandas Series, reshape it to a 2D array
    if isinstance(x, pd.Series):
        x = x.values.reshape(-1, 1)

    # number of training example and no. of features
    self.m , self.n = x.shape        # number of rows and columns

    # initiating the weight(slope) and bias(interept)

    self.w = np.zeros(self.n)
    self.b =0
    self.x = x
    self.y = y
    # implementing gradient descent

    for i in range(epochs):
      self.update_weights()

  def update_weights(self,): # function to update the parameters value based on the gradient descent

    y_predict = self.predict(self.x)

    # calculate the gradient
    dw = -(2*(self.x.T).dot(self.y - y_predict))/ self.m

    db = -2* np.sum(self.y - y_predict)/self.m

    # updating the weights

    self.w = self.w - self.learning_rate*dw
    self.b = self.b - self.learning_rate*db



  def predict(self,x):
    # If x is a pandas Series, reshape it to a 2D array
    if isinstance(x, pd.Series):
        x = x.values.reshape(-1, 1)
    return x.dot(self.w) + self.b