# -*- coding: utf-8 -*-
"""logistic regression model.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SxZCeaKRnUQEmBQE2bfGb3zN3phGQDhj
"""

import pandas as pd
import numpy as np
import sklearn as sk
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv('diabetes.csv')

df.head()

df.isna().sum()  # output clearly shows that there are no mising values

"""# Work flow of the logistics regression model #

1. set the learning rate and number of iterattion ; Initiate Random weight and bias value
2. built logistic regression function . ( sigmoid function )
3. update the parameter using the gradient descent .
(finally we will get the best model ie best weight and best bias value as it has the minimum cost function )
4. build he predict function to determine the class of the data point.
"""

# Building Logistics regression
class Logistic_Regression():         # logistics regresson is an object and class is the template eg. car is an object its blueprint is the template
    def __init__(self, learning_rate, no_of_iterations):
        self.learning_rate = learning_rate
        self.no_of_iterations = no_of_iterations
# fit function to train the model on dataset
    def fit(self, X, Y):
        self.m, self.n = X.shape    # m is no. of rows and n is no. of columns (no. of rows is no. of data points and no. of column is no. of input feature # x is the columns expect for the output data
        self.w = np.zeros(self.n)
        self.b = 0
        self.X = X
        self.Y = Y

        # Impleementing gradient descent ( trying to find the updated weight and bias value (optimum))

        for i in range(self.no_of_iterations):
            self.update_weights()

    def update_weights(self):
      # sigmoid function
        Y_hat = 1 / (1 + np.exp(-(self.X.dot(self.w) + self.b))) # np.exp is the exponential function # .dot implies matrix multiplication in numpy

        # derivatives

        dw = (1/self.m)*np.dot(self.X.T, (Y_hat - self.Y))  # we take X transpose to abide by matrix multiplication rule of no. of col in first equal to no. of rows of second

        db = (1/self.m)*np.sum(Y_hat - self.Y)

        # updating the weight and bias usinf gradient descent

        self.w = self.w - self.learning_rate * dw
        self.b = self.b - self.learning_rate * db

    def predict(self, X):   # sigmoid function and decision boundary ( decision boundary is that is y_hat value is greater than 0.5 than 1 or it should be zero since its an classification model with binary output of yes or no  so we dont he outpit to be 0.8 or somthing we want to be either 1 or 0)
        Y_pred = 1 / (1 + np.exp(-(X.dot(self.w) + self.b)))
        Y_pred = np.where(Y_pred > 0.5, 1, 0)
        return Y_pred

import numpy as np
from sklearn.utils.class_weight import compute_class_weight

class Advanced_Logistic_Regression():

    def __init__(self, learning_rate=0.01, no_of_iterations=1000,
                 lambda_reg=0.01, class_weight='balanced'):
        """
        Initializes the model with learning parameters and regularization.
        lambda_reg: L2 regularization strength (prevents overfitting).
        class_weight: 'balanced' or None.
        """
        self.learning_rate = learning_rate
        self.no_of_iterations = no_of_iterations
        self.lambda_reg = lambda_reg
        self.class_weight = class_weight
        self.cost_history = []
        self.weights_ = None
        self.bias_ = None

    def fit(self, X, Y):

        self.m, self.n = X.shape
        self.X = X
        self.Y = Y

        # --- 1. Class Weighting for Imbalance (CRITICAL) ---
        if self.class_weight == 'balanced':
            # Calculates weights inversely proportional to class frequencies
            classes = np.unique(Y)
            weights = compute_class_weight(class_weight='balanced', classes=classes, y=Y)
            self.class_weights_dict = dict(zip(classes, weights))
            # Create a vector of weights corresponding to each training sample
            self.sample_weights = np.array([self.class_weights_dict[label] for label in Y])
        else:
            self.sample_weights = np.ones(self.m)

        # Initialize weights (w) and bias (b)
        self.w = np.zeros(self.n)
        self.b = 0

        # --- 2. Implementing Gradient Descent with L2 Regularization ---
        for i in range(self.no_of_iterations):
            self.update_weights()
            self.cost_history.append(self.cost_function())

        self.weights_ = self.w
        self.bias_ = self.b

    def update_weights(self):

        # Calculate the linear model and sigmoid probability (Y_hat)
        linear_model = self.X.dot(self.w) + self.b
        Y_hat = 1 / (1 + np.exp(-linear_model))

        # Error term, weighted by class importance
        error = Y_hat - self.Y
        weighted_error = error * self.sample_weights

        # Calculate the Gradient (dw)
        # 1. Base Gradient (Same as yours, but weighted)
        dw_base = (1 / self.m) * np.dot(self.X.T, weighted_error)

        # 2. Add L2 Regularization Term (Prevents Overfitting)
        dw_reg = self.lambda_reg * self.w

        dw = dw_base + dw_reg

        # Calculate the Gradient (db)
        db = (1 / self.m) * np.sum(weighted_error)

        # Update the Weights and Bias
        self.w = self.w - self.learning_rate * dw
        self.b = self.b - self.learning_rate * db

    def cost_function(self):
        """Calculates the Binary Cross-Entropy (Log-Loss) cost."""
        linear_model = self.X.dot(self.w) + self.b
        Y_hat = 1 / (1 + np.exp(-linear_model))

        # Basic Cross-Entropy Loss (Note: The calculation for training must also incorporate L2 term
        # if using regularization, but for simplicity, we calculate the data-fit loss here)
        cost = -(1 / self.m) * np.sum(
            self.Y * np.log(Y_hat + 1e-9) + (1 - self.Y) * np.log(1 - Y_hat + 1e-9)
        )
        # Add L2 penalty to the cost for reporting
        l2_penalty = (self.lambda_reg / (2 * self.m)) * np.sum(self.w**2)

        return cost + l2_penalty


    def predict_proba(self, X):
        """Returns the probability of the positive class (1)."""
        return 1 / (1 + np.exp(-(X.dot(self.w) + self.b)))

    def predict(self, X, threshold=0.5):
        """
        Returns the binary prediction based on a customizable threshold.
        This is crucial for fraud detection where the threshold is often < 0.5.
        """
        Y_pred_proba = self.predict_proba(X)

        # Apply the decision boundary
        Y_pred = np.where(Y_pred_proba >= threshold, 1, 0)
        return Y_pred