# -*- coding: utf-8 -*-
"""ML project (Sales).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vV5PzvOIhaoImHwCZdeI8OI2F9141RVZ
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.cluster import KMeans
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import mean_squared_error, r2_score

df = pd.read_excel('advertising_sales_data.xlsx')
df.head()

from sklearn.impute import SimpleImputer
import numpy as np

# Separate numerical and non-numerical columns
numerical_cols = df.select_dtypes(include=np.number).columns
non_numerical_cols = df.select_dtypes(exclude=np.number).columns

# Identify numerical columns that are not entirely NaN
imputable_numerical_cols = [col for col in numerical_cols if not df[col].isnull().all()]

# Impute numerical columns with the mean (only those that are not entirely NaN)
if imputable_numerical_cols:
    imputer_numeric = SimpleImputer(missing_values=np.nan, strategy='mean')
    df[imputable_numerical_cols] = imputer_numeric.fit_transform(df[imputable_numerical_cols])

df

"""Question 1 : What is the average amount spent on TV advertising in the dataset?

"""

avg_tv_spending = df['TV'].mean()
print(f"The average amount spent on TV advertising is: ${avg_tv_spending:.2f}")
#

"""Question 2 : What is the correlation between radio advertising expenditure and product sales?

"""

correlation = df['Radio'].corr(df['Sales'])
print(f"The correlation between radio advertising expenditure and product sales is: {correlation:.2f}")

"""Question 3: Which advertising medium has the highest impact on sales based on the dataset?

"""

#Finding standardized coefficients
X = df[['TV', 'Radio', 'Newspaper']]
y = df['Sales']

scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)
model_impact = LinearRegression().fit(X_scaled, y)
impact = pd.Series(model_impact.coef_, index=X.columns)

print("Standardized Coefficients (Impact Ranking):")
print(impact.sort_values(ascending=False))

"""Question 4: Plot a linear regression line that includes all variables (TV, Radio, Newspaper) to predict Sales, and visualize the model's predictions against the actual sales values.

"""

X = df[['TV', 'Radio', 'Newspaper']]
y = df['Sales']
#Train/Test Split for the Prediction Model
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

model = LinearRegression()
model.fit(X_train, y_train)
y_pred = model.predict(X_test)

#Visualization: Predictions vs Actual
plt.figure(figsize=(10, 6))
plt.scatter(y_test, y_pred, color='blue', alpha=0.6, label='Data Points')

# The "Perfect Prediction" Line (y = x)
line_coords = [y.min(), y.max()]
plt.plot(line_coords, line_coords, color='red', lw=2, linestyle='--', label='Perfect Fit')

plt.xlabel('Actual Sales')
plt.ylabel('Predicted Sales')
plt.title('Actual vs Predicted Sales: Multiple Linear Regression')
plt.legend()
plt.grid(True)
plt.show()

# 5. Evaluate
print(f"R-squared Score: {r2_score(y_test, y_pred):.4f}")
r2_raw = r2_score(y_test, y_pred)

"""Question 5:How would sales be predicted for a new set of advertising expenditures: $200 on TV, $40 on Radio, and $50 on Newspaper?

"""

new_expenditures = pd.DataFrame({
    'TV': [200],
    'Radio': [40],
    'Newspaper': [50]
})

prediction = model.predict(new_expenditures)

print(f"The predicted sales for this budget is: {prediction[0]:.2f}")

"""Question 6 : How does the performance of the linear regression model change when the dataset is normalized?

"""

scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

model_scaled = LinearRegression()
model_scaled.fit(X_train_scaled, y_train)
y_pred_scaled = model_scaled.predict(X_test_scaled)
r2_scaled = r2_score(y_test, y_pred_scaled)

# COMPARISON OUTPUT
print("PERFORMANCE METRICS:")
print(f"R-squared (Raw Data):        {r2_raw:.6f}")
print(f"R-squared (Normalized Data): {r2_scaled:.6f}")
print("-" * 30)
print("COEFFICIENT COMPARISON:")
coef_df = pd.DataFrame({
    'Feature': X.columns,
    'Raw Coefficients': model.coef_,
    'Normalized Coefficients': model_scaled.coef_
})
print(coef_df)

"""Question 7: What is the impact on the sales prediction when only radio and newspaper advertising expenditures are used as predictors?"""

#Finding standardized coefficients
X = df[[ 'Radio', 'Newspaper']]
y = df['Sales']

scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)
model_impact = LinearRegression().fit(X_scaled, y)
impact = pd.Series(model_impact.coef_, index=X.columns)

print("Standardized Coefficients (Impact Ranking):")
print(impact.sort_values(ascending=False))

X_full = df[['TV', 'Radio', 'Newspaper']]
model_full = LinearRegression().fit(X_full, y)
y_pred_full = model_full.predict(X_full)

X_reduced = df[['Radio', 'Newspaper']]
model_reduced = LinearRegression().fit(X_reduced, y)
y_pred_reduced = model_reduced.predict(X_reduced)

#  Compare Results
print(f"Full Model R^2:    {r2_score(y, y_pred_full):.4f}")
print(f"Reduced Model R^2: {r2_score(y, y_pred_reduced):.4f}")
print(f"Increase in MSE:   {mean_squared_error(y, y_pred_reduced) - mean_squared_error(y, y_pred_full):.2f}")

