# -*- coding: utf-8 -*-
"""ML project (Facebook).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/118Jvy8g9ZcoOnCbBOjxKmiYqAZVxDQOo
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.cluster import KMeans
from sklearn.linear_model import LinearRegression

df = pd.read_csv('Facebook_Marketplace_data.csv')
df.head()

from sklearn.impute import SimpleImputer

# Separating numerical and non-numerical columns
numerical_cols = df.select_dtypes(include=np.number).columns
non_numerical_cols = df.select_dtypes(exclude=np.number).columns

# Finding numerical columns that are not entirely NaN
imputable_numerical_cols = [col for col in numerical_cols if not df[col].isnull().all()]

# Imputing numerical columns with the mean (only those that are not entirely NaN)
if imputable_numerical_cols:
    imputer_numeric = SimpleImputer(missing_values=np.nan, strategy='mean')
    df[imputable_numerical_cols] = imputer_numeric.fit_transform(df[imputable_numerical_cols])

# Imputing non-numerical columns with the most frequent value, if they have NaNs
imputer_categorical = SimpleImputer(missing_values=np.nan, strategy='most_frequent')
for col in non_numerical_cols:
    if df[col].isnull().any():
        df[col] = imputer_categorical.fit_transform(df[[col]])

df

""" QUESTION 1: How does the time of upload (`status_published`)  affects the `num_reaction`?

"""

# Converting to datetime
df['status_published'] = pd.to_datetime(df['status_published'])

df['hour'] = df['status_published'].dt.hour
df['day_of_week'] = df['status_published'].dt.day_name()

hourly_engagement = df.groupby('hour')['num_reactions'].mean()

sns.lineplot(data=df, x='hour', y='num_reactions')
plt.title('Effect of Upload Hour on Reactions')
plt.show()

"""Question 2:Is there a correlation between the number of reactions (num_reactions) and other engagement metrics such as comments (num_comments) and shares (num_shares)? If so, what is the strength and direction of this correlation?

"""

metrics = ['num_reactions', 'num_comments', 'num_shares', 'num_likes', 'num_loves']
corr_matrix = df[metrics].corr()
print(corr_matrix)

plt.figure(figsize=(10, 8))
sns.heatmap(corr_matrix, annot=True, cmap='coolwarm', fmt=".2f")
plt.title('Correlation Matrix of Engagement Metrics')
plt.show()

"""Question 3 : Use the columns status_type, num_reactions, num_comments, num_shares, num_likes, num_loves, num_wows, num_hahas, num_sads, and num_angrys to train a K-Means clustering model on the Facebook Live Sellers dataset."""

X = df.iloc[:,[1,3,4,5,6,7,8,9,10,11]].values
print(X)

# Implementing one hot encoding

from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder',OneHotEncoder(),[0])],remainder='passthrough')
X = np.array(ct.fit_transform(X))
print(X)

from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X = sc.fit_transform(X)
print(X)

wcss = []

for i in range(1,11):
  kmeans = KMeans(n_clusters=i,init='k-means++',random_state=42)
  kmeans.fit(X)
  wcss.append(kmeans.inertia_)

"""Question 4: Use the elbow method to find the optimum number of clusters"""

plt.plot(range(1,11),wcss)
plt.title('The Elbow Method')
plt.xlabel('Number of clusters')
plt.ylabel('WCSS')
plt.show()

kmeans= KMeans(n_clusters=6,init='k-means++',random_state=42)
y_kmeans = kmeans.fit_predict(X)

"""Question 5 : What is the count of different types of posts in the dataset?

"""

post_counts = df['status_type'].value_counts()

print("Count of different post types:")
print(post_counts)

# To see the percentage distribution
print("\nPercentage distribution:")
print(df['status_type'].value_counts(normalize=True) * 100)

plt.figure(figsize=(8, 5))
sns.countplot(data=df, x='status_type', palette='viridis')
plt.title('Distribution of Post Types')
plt.xlabel('Status Type')
plt.ylabel('Number of Posts')
plt.show()

"""Question 6 : What is the average value of num_reaction, num_comments, num_shares for each post type?"""

# Grouping by status_type and calculating the mean for specific columns
averages = df.groupby('status_type')[['num_reactions', 'num_comments', 'num_shares']].mean()

# Sorting by reactions to see which type is most popular
print(averages.sort_values(by='num_reactions', ascending=False))