# -*- coding: utf-8 -*-
"""VaR.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vzqb0rICRleOnIcuvWAuaTR-UZ-cJaCQ
"""

import yfinance as yf
import pandas as pd

"""# Define the tickers for the three stocks
TICKERS = ["RELIANCE.NS", "TCS.NS", "HDFCBANK.NS"]

# Download 5 years of daily data (from today back 5 years)
# The 'download' function returns a multi-indexed Pandas DataFrame.
data = yf.download(TICKERS, period="5y")

# Display the first few rows to confirm success
print(data.head())
"""

data = yf.download(['Reliance.NS','TCS.NS','HDFCBANK.NS'],period='5y')
data.head()

"""# Select only the 'Close' price column for all three stocks
closing_prices = data['Close']

# Verify the result—this should show only the date and the three closing prices
print("\n--- Cleaned Closing Prices ---")
print(closing_prices.tail())

# Check the shape to confirm 5 years of data (approx 1200+ rows) and 3 columns
print(closing_prices.shape)
"""

closing_prices = data['Close']

closing_prices.shape

closing_prices.head()

"""Certainly! Calculating Daily Log Returns is a common step in financial analysis, and I can explain both the 'what' and 'why', along with the 'how'.

What are Daily Log Returns?
Log returns (also known as continuously compounded returns) measure the percentage change in an asset's price over time, but they use the natural logarithm. The formula for a daily log return is:

Log Return = ln(P_today / P_yesterday)

Where:

P_today is the closing price of the stock on the current day.
P_yesterday is the closing price of the stock on the previous day.
ln denotes the natural logarithm.
Why are we doing this?
Log returns are preferred over simple percentage returns for several reasons, especially in statistical and quantitative finance:

Additivity: Log returns are additive over time. If you want to find the return over a week, you can simply sum the daily log returns for that week. Simple returns are multiplicative.
Symmetry: Log returns are symmetric. A 10% gain followed by a 10% loss (or vice versa) results in a return of approximately zero when using log returns, which is more intuitive for many models.
Statistical Properties: Log returns often conform more closely to a normal distribution, particularly for actively traded assets. This is very useful because many statistical models (like those for risk assessment or option pricing) assume normally distributed data.
Mathematical Convenience: They simplify many mathematical operations in finance, making calculations for portfolio theory, volatility, and risk management more straightforward.
How to calculate using np.log and shift():
closing_prices.shift(1): The shift(1) method in Pandas will take your closing_prices DataFrame and move all its values down by one row. This effectively aligns each day's closing price with the previous day's closing price.
closing_prices / closing_prices.shift(1): This division calculates the daily price ratio (P_today / P_yesterday) for each stock.
np.log(...): Finally, np.log() (from the NumPy library) applies the natural logarithm to each element of this price ratio, giving you the daily log returns.
Let's generate the code to calculate these log returns for your stocks:

The daily log returns have been successfully calculated! Here's what you're seeing in the output:

Date: This is the trading date for which the log return is calculated.
HDFCBANK.NS, RELIANCE.NS, TCS.NS: These are your stock tickers, and the values below them are the calculated daily log returns for each stock on that specific date.
Why NaN for the first row?
You'll notice that the first row (2020-12-09) contains NaN (Not a Number) values. This is expected because to calculate the log return for any given day, we need the closing price from the previous day. Since there's no 'previous' day in your dataset before the first date, the calculation can't be performed, resulting in NaN.

What do the other numbers mean?
For the subsequent dates, the numbers represent the natural logarithm of the ratio of today's closing price to yesterday's closing price. For example:

On 2020-12-10, HDFC Bank had a daily log return of approximately -0.015288. This indicates a slight decrease in price from the previous day.
On 2020-12-14, TCS had a daily log return of approximately 0.005052. This indicates a slight increase in price from the previous day.
These values are now ready for further statistical analysis, as log returns have favorable properties for financial modeling!


"""

import numpy as np

# Calculate daily log returns
daily_log_returns = np.log(closing_prices / closing_prices.shift(1))
daily_log_returns = daily_log_returns.dropna()

# Display the first few rows of the daily log returns
print("\n--- Daily Log Returns ---")
print(daily_log_returns.head())

import numpy as np

# Define equal weights for each stock
num_stocks = len(daily_log_returns.columns)
weights = np.array([1/num_stocks] * num_stocks)

# Calculate weighted daily log returns for the portfolio
# We use dot product to multiply each stock's return by its weight and sum them up
portfolio_daily_log_returns = daily_log_returns.dot(weights)

print("\n--- Initial Portfolio Weights ---")
for i, stock in enumerate(daily_log_returns.columns):
    print(f"{stock}: {weights[i]:.2%}")

print("\n--- First 5 rows of Portfolio Daily Log Returns ---")
print(portfolio_daily_log_returns.head())

print("\n--- Last 5 rows of Portfolio Daily Log Returns ---")
print(portfolio_daily_log_returns.tail())

import numpy as np

# Define the confidence level (e.g., 95% or 99%)
confidence_level = 0.95

# Calculate the percentile (e.g., for 95% confidence, we want the 5th percentile)
# The percentile is 1 - confidence_level
percentile = 1 - confidence_level

# Sort the portfolio daily log returns
sorted_returns = portfolio_daily_log_returns.sort_values(ascending=True)

# Calculate the Historical VaR
# The VaR is the value at the specified percentile
historical_var = np.percentile(sorted_returns, percentile * 100)

# For easier interpretation, VaR is usually expressed as a positive number or percentage loss
# Multiplying by -1 makes it a positive loss value
print(f"--- 1-Day Historical VaR at {confidence_level:.0%} Confidence Level ---")
print(f"VaR: {-historical_var:.4f} (or {-historical_var * 100:.2f}%)")

# Explain what the result means
print(f"\nThis means that over a 1-day period, there is a {percentile * 100:.0f}% chance that your portfolio could lose {-historical_var * 100:.2f}% or more of its value, based on historical data.")
print(f"Conversely, there is a {confidence_level:.0%} chance that your portfolio will not lose more than {-historical_var * 100:.2f}% of its value.")

import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# Calculate the first quantile (25th percentile) of the portfolio daily log returns
first_quantile = np.percentile(portfolio_daily_log_returns, 25)

print(f"--- First Quantile (25th Percentile) of Portfolio Daily Log Returns ---")
print(f"First Quantile: {first_quantile:.4f} (or {first_quantile * 100:.2f}%)")

# Visualize the distribution of portfolio daily log returns with the first quantile marked
plt.figure(figsize=(10, 6))
sns.histplot(portfolio_daily_log_returns, bins=50, kde=True, color='skyblue')
plt.axvline(first_quantile, color='red', linestyle='--', label=f'1st Quantile ({first_quantile*100:.2f}%)')
plt.title('Distribution of Portfolio Daily Log Returns with 1st Quantile')
plt.xlabel('Daily Log Returns')
plt.ylabel('Frequency')
plt.legend()
plt.grid(True, linestyle=':', alpha=0.7)
plt.show()